name: 'dependency'

on:
  issues:
    types: [labeled, unlabeled, reopened]
    
permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dessant/support-requests@v2.1.2
        with:
          support-label: 'dependency'
          issue-comment: >
            :wave: Hello @{issue-author}, your issue report doesn't seem to apply to Additional Guns, but rather one of its dependencies. \
            Dependency issue trackers:
            * [MrCrayfish's Gun Mod](https://github.com/MrCrayfish/MrCrayfishGunMod/issues)
            * [Framework](https://github.com/MrCrayfish/Framework/issues) (1.18.x and above)
            * [Obfuscate](https://github.com/MrCrayfish/Obfuscate/issues) (1.16.x)
          close-issue: true
          lock-issue: false
          
