name: 'eol'

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [labeled, unlabeled, reopened]
    
permissions:
  issues: write

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: dessant/support-requests@v2.1.2
        with:
          support-label: 'eol'
          issue-comment: >
            :wave: Hello @{issue-author}, you appear to be reporting an issue for a version we no longer support.
            Try updating to a newer version of the game and open a new issue if the issue still applies.
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'
