name: 'eol'

on:
  issues:
    types: [labeled, unlabeled, reopened]
    
permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dessant/support-requests@v2
        with:
          support-label: 'eol'
          issue-comment: >
            :wave: Hello @{issue-author}, you appear to be reporting an issue for a version we no longer support.
            Try updating to a newer version of the game and open a new issue if the issue still applies.
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'resolved'
