name: 'legacy version'

on:
  issues:
    types: [labeled, unlabeled, reopened]
    
permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dessant/support-requests@v2
        with:
          support-label: 'legacy version'
          issue-comment: >
            :wave: Hello @{issue-author}, it seems that you are asking for a backport to an older Minecraft version.
            Unfortunately there are no plans on backporting the mod to discontinued versions of the game.
            The team would like to dedicate their time moving forward instead.
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'
          
