name: 'off-topic'

on:
  issues:
    types: [labeled, unlabeled, reopened]
    
permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dessant/support-requests@v2
        with:
          support-label: 'off-topic'
          issue-comment: >
            :wave: Hello @{issue-author}, we use the issue tracker exclusively for bug reports.
            However, this seems to be better suited for our Discord server, Discussions tab or CurseForge comment section.
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'
          
